print("Hello, World,  NAVEEN  sample nginx image")
print("1. Create a Github repo - put YAML and all files in the same repo" )
print("2. Put a Python script inside an image that prints 'Hello World'")
print("3. Create a Dockerfile" )
print("4. Create an image and push it to Docker registry")
print("5. Create a workflow that automates the above four steps")
print("6. Create a webhook event source, sensor with workflow from step 5")
print("7. Make changes in the Python script")
