apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: python-app
spec:
  entrypoint: python-app
  templates:
    - name: python-app
      container:
        image: naveenbalagouni/python-docker-app  # Ensure this points to the updated image
        command: ["/bin/sh", "-c", "python-app/app.py"]
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
