apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: python-app-workflow
  namespace: test
spec:
  entrypoint: python-app
  templates:
    - name: python-app
      container:
        image: naveenbalagouni/python-docker-app
        command: ["python", "app.py"]  # This should be correct, as long as app.py is in /usr/src/app
