# Use official Python image from Docker Hub
FROM python:3.9-slim

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy the contents of the 'python-app' directory into the container
COPY python-app /usr/src/app

# Command to run the Python script
CMD ["python", "app.py"]
